obj-$(CONFIG_MT6370_PMU_DSV) += mtk_6730_poweric.o

EXTRA_CFLAGS +=-Idrivers/staging/android \
		-Idrivers/atfdriver \
		-Idrivers/devkit/lcdkit/lcdkit3.0 \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/mtk/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/mtk/adapt \
		-Idrivers/misc/mediatek/lcm/inc
